### PR TITLE
Remove quotes

### PR DESCRIPTION
**Pull request by RabeaGleissner**
I'd like to remove the quotes that are displayed when we run bosco commands. 

Reasons:
- not everyone knows the A-Team and that Bosco is a member
- the quotes are sometimes a bit offensive (e.g. being told `I'm glad I didn't know you when I was a kid` or being called a `crazy ass fool`)
- it feels a bit alienating to have these kinds of in-jokes displayed by a tool that is so widely used across the whole of Tes engineering when not everyone understands them

### CODE REVIEW

**Comment by danielabel** [comment]
build failing :(

**Comment by RabeaGleissner** [comment]
Oh dear, CI is failing! Looks like it has been failing for a month!

**Comment by rouanw** [comment]
I've fixed the build and rebased.

**Comment by RabeaGleissner** [comment]
Thanks a lot for fixing @rouanw !

**Pull request merged**
