### PR TITLE
add new command to report on repos not on master

### PR DESCRIPTION
**Pull request by andy-duncan**
based off of status command.

use 'git branch --list' to show all branches, and checked out branch is marked with a '*'

only show results for branches not on master

### CODE REVIEW

**Comment by codeaholics** [comment]
You should really do that with `git rev-parse --abbrev-ref HEAD` rather than parsing `git branch`

**Comment by andy-duncan** [comment]
nice. I poked around, and didn't find anything better immediately.

other than being shorter and more direct, any reason why the other approach might fail us at any point?

**Comment by andy-duncan** [comment]
(out of interest; incorporating your suggestion)

**Comment by codeaholics** [comment]
`git branch` is a porcelain command - a user-focused command. The output format could change between git versions. `git rev-parse` is a plumbing command - designed for scripting, etc. The output of this is much less likely to change. Also, it saves you a regexp match :-) Note in both cases that you're getting the local branch name, not the remote branch name. I realise that for most people they are the same, but they don't have to be.

**Comment by andy-duncan** [comment]
ok, @codeaholics. thanks for the insight. as far as different remote branch names, I think this is all I am after for now, but I guess it could be extended.

**Comment by codeaholics** [comment]
Most people won't even notice :-) I think this command is a good idea. Would certainly have been useful when I was working on resources with, like, 1,000 microservices checked out.

**Pull request merged**
