### PR TITLE
Run 'nvm' and 'nvm use'  before watch commands

### PR DESCRIPTION
**Pull request by andy-duncan**
@cliftonc would you have a quick look at this, please?

### CODE REVIEW

**Comment by andy-duncan** [comment]
@vaneetkaur @BorePlusPlus

**Comment by cliftonc** [comment]
lgtm

**Comment by geophree** [comment]
I don't think this correctly deals with watch commands that are arrays.  It also doesn't correctly set `commandForLog`, not at all for watch commands, and not including the extra `nvm` stuff for.  You shouldn't have changed the tests, they should still pass even with the `nvm` stuff.  I think your code relies on there only being one string in the array, and the fact that if you concat a one-element array and a string, it happens to work.  e.g.
```js
"foo" + ["bar"] === "foobar"
```

**Comment by cliftonc** [comment]
Good point @geophree - @andy-duncan @charlieharris1 can you take another look tomorrow?

**Comment by charlieharris1** [comment]
Here is the command for the logging fix: https://github.com/tes/bosco/pull/139

@geophree can you help us to understand your use case for watch to handle arrays? @andy-duncan has looked through most, if not all, of the watch commands used across tes repos and can only find one usage in bosco for testing purposes.

**Comment by geophree** [comment]
Support for arrays is provided so that people can avoid shell escaping bugs.  Also, it was supported in the past, so we should either continue to support it, or error when we encounter it.

**Pull request merged**
