### PR TITLE
If container running, stop it before removal #247

### PR DESCRIPTION
**Pull request by ksnll**
We can either use force for removal, or just check if it's running and stop it before removing

### CODE REVIEW

**Comment by cliftonc** [comment]
:awesome: will check this morning but lgtm

**Comment by cliftonc** [comment]
Sorry for delay @ksnll - released with 0.5.116

**Comment by ksnll** [comment]
great 💯

**Comment by cliftonc** [comment]
@sithmel now seeing these errors:

```
(node:8787) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: (HTTP code 404) no such container - No such container: app-user-profile
--
```

**Comment by cliftonc** [comment]
Will see if I can figure this out this morning.

**Comment by cliftonc** [comment]
Fixed by being a bit more defensive: https://github.com/tes/bosco/commit/dc040769155eb4afc1db6dd575a11418d936e3dc

**Pull request merged**
