### PR TITLE
[DO NOT MERGE] Changes to facilitate local https.

### PR DESCRIPTION
**Pull request by geophree**
These changes help with local https, but they're not ready to merge yet.

### CODE REVIEW

**Comment by geophree** [comment]
@cliftonc I don't really understand the interplay between `this.config.get('aws:cdn')`, `this.config.get('cdn:port')`, `bosco.config.cdn.url`, and the other `cdn` stuff.  See:
https://github.com/tes/bosco/blob/f7b628a910fb72cca6a11bd2b3286befdbc92597/index.js#L459-L499
and
https://github.com/tes/bosco/blob/f7b628a910fb72cca6a11bd2b3286befdbc92597/commands/cdn.js#L118
I'd like to add a config param that allows a full url (specifically `http://www.tes-local.com/cdn` (changed to https later).  Where is the best place to do that?

**Comment by cliftonc** [comment]
The CDN url is used in two ways - when a service is running locally it needs to resolve to the local CDN (e.g. the service is running locally), if it is running in a container then it needs to resolve to the AWS cdn url.

So, not local:

https://github.com/tes/bosco/blob/f7b628a910fb72cca6a11bd2b3286befdbc92597/index.js#L464-L466

The `cdn:port` and `cdn:host` were intended as optional over-rides, most engineers won't have that config set.

I'd propose creating a new config (as you say) of `cdn:url`, but still defaulting to something sensible so it doesn't break everyone.  No need to retain the old ones.

**Comment by geophree** [comment]
Should we change 
https://github.com/tes/bosco/blob/f7b628a910fb72cca6a11bd2b3286befdbc92597/commands/cdn.js#L118
to
```js
var baseCdn = bosco.config.get('cdn:remoteUrl') || 'https://duqxiy1o2cbw6.cloudfront.net/tes';
```
and
https://github.com/tes/bosco/blob/f7b628a910fb72cca6a11bd2b3286befdbc92597/index.js#L468-L474
to
```js
return bosco.config.get('cdn:url') || 'http://localhost:7334';
```

It will require people to add config for the local cdn url, but we can default it to `http://www.tes-local.com/cdn` (or `https`) once we get all this working.

**Comment by cliftonc** [comment]
Sure - that should work.

**Comment by geophree** [comment]
I tested it locally and it works when I add the cdn url config to my bosco json.  I suppose we could also add it to the bosco config in the team repos.

**Comment by cliftonc** [comment]
lgtm - I think we should just add to the engineering guide as a one liner when setting up bosco.

```
bosco config set cdn:remoteUrl https://www.tes-local.com/cdn
```

**Comment by geophree** [comment]
It'd actually be
```bash
bosco config set cdn:url https://www.tes-local.com/cdn
```

**Pull request merged**
