### PR TITLE
Ensure latest version

### PR DESCRIPTION
**Pull request by rouanw**
I was recently caught out because my local `nginx` was misbehaving and I didn't notice that `bosco` was out of date (on the node version used for the project I was running). Noticing would have saved me a heap of time, so from now on I want Bosco to be stricter with me.

`bosco` already checks to see whether you are running the latest version. This PR introduces a 'strict mode', which will kill the current process if you're not.

```js
// bosco config
{
  // ...
  "strict": true
}
```

Note that the version check is asynchronous, so there will be times when `bosco` doesn't find out in time that it's out of date.

Feel free to suggest better names for the setting 🐶

/cc @cliftonc @andy-duncan

### CODE REVIEW

**Comment by cliftonc** [comment]
Looks fine, but the name has connotations around 'use strict' for me.

How about: 

```
  "ensureLatestVersion": true
```

**Comment by rouanw** [comment]
Thanks @cliftonc. I've updated the naming.

**Comment by andy-duncan** [comment]
nice!!

**Comment by cliftonc** [comment]
Published with 0.5.87.

Note that you can set this config after upgrading with:

```
bosco config set ensureLatestVersion true
```

**Pull request merged**
