### PR TITLE
Libraries

### PR DESCRIPTION
**Pull request by cliftonc**
Define vendor libraries outside of the usual `files` or `assets`, these get pushed up to a static `vendor/library` folder that does not have the build number of the service.

Example of service:  https://github.com/tes/service-site-assets/blob/libraries-example/bosco-service.json#L21-L30

### CODE REVIEW

**Comment by cliftonc** [comment]
@bettiolo @sithmel - this means the libraries end up on S3 as:

`{{cdnBaseUrl}}}/vendor/library/library-123.js`

e.g.

`https://duqxiy1o2cbw6.cloudfront.net/tes/vendor/library/library-123.js`

This means it is absent of any versioning within the service (e.g. site-assets) and relies entirely on versioning within the vendor library (not an issue).  It respects paths etc. as you would expect.   You can bundle libs together and send them up as well (e.g. the react bundle).

We can easily add a 'cx-library' directive, where we just put the path in and let page composer add the `{{cdnBaseUrl}}}/vendor/library/` part, avoids every service having to know what `{{cdnBaseUrl}}` is (which is in page composer config at present).  Optional though I think would make the transition easier.

**Comment by geophree** [comment]
Does that run the risk of multiple different services overwriting each other with what they think is the "correct" version of their library (assuming they're doing some building of the library and not just pushing it whole-hog).  Is there some way to add a hash to the path without totally breaking relative paths?  So if two services push `fontawesome-4.5.0.min.css` but they are actually different files, one ends up at `https://duqxiy1o2cbw6.cloudfront.net/tes/vendor/library/a09bf7/fontawesome-4.5.0.min.css` and the other at `https://duqxiy1o2cbw6.cloudfront.net/tes/vendor/library/c89de4/fontawesome-4.5.0.min.css`.  I don't think that solution will actually work. but do you understand the issue I'm worried about?

**Comment by cliftonc** [comment]
Yes, it needs some discipline - e.g. put all libraries in site assets.

**Comment by cliftonc** [comment]
Merging now, it is a zero effect change until the libraries config is added to a `bosco-service.json` file.

**Comment by bettiolo** [comment]
Great, this is cool as we don't invalidate the browser cache any more on every release of service-site-assets!

**Pull request merged**
