### PR TITLE
Re-use container vs re-create to close #216

### LINKED ISSUE #216: docker error when running npm run -d cdn in resources team
screen shot 2017-03-03 at 15 37 55

### PR DESCRIPTION
**Pull request by cliftonc**
Works for me locally, can't see why this isn't ok.  @geophree @bettiolo

### CODE REVIEW

**Comment by geophree** [comment]
The reason we remove the container is so that we are sure we get a fresh one, does this do that as well, or will it still have data from the last time it ran?

**Comment by cliftonc** [comment]
Why don't we want the data from the last time it ran as the default?  It would make a lot of local dev easier if you knew that your data would be persisted ... until you didn't want it to be?  

I guess if we leave it as is the issue Marco has (which appears to be a docker issue related to trying to remove a running container) will persist.

**Comment by geophree** [comment]
If we want to persist data, we should do it with something more durable, like data volumes, or something like that.  Until we do that, I think it's better to have a bosco stop and start clean the slate (as it does with js services).  We already have enough problems coming from things not always being consistent.

**Comment by cliftonc** [comment]
Any suggestions to how we can avoid the issue?  Perhaps a forced remove?

**Comment by geophree** [comment]
That was my thought.  Haven't looked into how to do that with our library though.

**Comment by bettiolo** [comment]
We shouldn't store data inside docker containers as that would be against it's best practices

**Comment by cliftonc** [comment]
Well, I was thinking it may make more sense to have the `start` just use the existing container (data and all), but `pull` clear it out - as this feels more consistent with what we do in other areas.  But, I don't have really strong opinions on this, I was trying to fix the other bug and opened this can of worms.  If we are happy with having the other bug stay open we can park this and leave as is.

For the 'local' docker instances that are just used for dev, we have always had data in the containers @bettiolo - but we destroy them all the time as @geophree describes, so it makes no sense to map external volumes etc. (which were horrible in earlier versions of docker on mac anyway).

**Comment by cliftonc** [comment]
This doesn't appear to be a problem anymore, parking.

**Pull request closed without merging**
