### PR TITLE
s3push fix

### LINKED ISSUE #98: A failed app build should fail the jenkins build
eg. if the bosco build maps to a gulp build which fails, the whole jenkins build should fail

### PR DESCRIPTION
**Pull request by geophree**
Improve error handling in `ExternalBuild`, `StaticUtils`, and `s3push`.  Add comprehensive tests for `ExternalBuild`, and some tests for `s3push` and `StaticUtils`.  Should fix #98.

### CODE REVIEW

**Comment by geophree** [comment]
@cliftonc @dbellizzi Take a look at this?  I was going to push it today, but was distracted by other work.

**Comment by geophree** [comment]
Added two returns, and checked for global command after local and warned when we override local with global.

**Comment by cliftonc** [comment]
Haven't had much of a chance to review with everything going on, but if you & Dom are OK then ship it.

**Comment by geophree** [comment]
I was waiting until all the launches died down.  I'll merge this early next week.

**Comment by cliftonc** [comment]
Is this good to go @geophree ?

**Comment by geophree** [comment]
This should be ready.  Well tested with unittests, but I don't have any experience with running s3push.  Also, it was US & tes.com launch, then I got pulled into the google sso stuff, then I was(/am) on vacation.

**Comment by cliftonc** [comment]
Ok, I'll check with real live projects and merge if it all looks good - enjoy your vacation.

**Comment by geophree** [comment]
I have commits to fix #55 #64 and #106 that are held up on this.  I may be able to factor around it, but I'd prefer to just PR them as-is.

**Comment by cliftonc** [comment]
Sorry for the delay - tested on site assets, works perfectly.  If gulp build fails we now get a non zero exit code.
screen shot 2015-10-01 at 06 47 36

**Comment by cliftonc** [comment]
If build succeeds, works perfectly.
screen shot 2015-10-01 at 06 48 05

**Pull request merged**
