### PR TITLE
Only run the current project when in service folder

### PR DESCRIPTION
**Pull request by gabceb**
I've seen way too many people `bosco run`ning the s***t out of 70 repos when all they wanted to do was run the project on their cwd. 

Note that we will still run all if you call `bosco run` from the workspace root folder

@geophree

### CODE REVIEW

**Comment by orangejuicecoder** [comment]
lgtm

**Comment by gabceb** [comment]
Im going to make another change before this gets merged to make sure we only use the current directory if no -r or tag is passed

**Comment by dbellizzi** [comment]
I generally like this.  Missing a -r is pretty common and if you are using "stop" or "restart" stops or restarts everything, taking some time.  Having it work on the current dir makes a lot of sense in the workflow

**Comment by gabceb** [comment]
I pushed some more changes. The good news is that I am now using `bosco.checkInService();` instead of hacking cwd myself. The bad news is that I had to add some more code to make sure I didn't get a tag or repo options on the command. It would be great if I could peek into the original list of options and make sure they were not passed but could not figure out how to do so.

Anyways, this is good to merge

**Comment by gabceb** [comment]
first travis failed due to me pushing to the upstream remote (this) instead of my origin remote (gabceb/bosco) so we can ignore

**Comment by cliftonc** [comment]
There is already a tag ```-s``` that runs only current service.  It's what Bosco uses on Jenkins.

**Comment by cliftonc** [comment]
https://github.com/tes/bosco/blob/master/bin/bosco.js#L38

**Comment by cliftonc** [comment]
Anyway, it doesn't break that behaviour and is more of a sensible default, so will merge and release.

**Comment by cliftonc** [comment]
@gabceb bosco cdn now follows the same rule, and uses the dependency tree to decide what to cdn'ify.

https://github.com/tes/bosco/commit/cd4c8410dfea1317acfdf764a590e23dbe350c2e

**Pull request merged**
